Google profile:  {
    id: '111505623946860825036',
    displayName: 'ismail mammeri',
    name: { familyName: 'mammeri', givenName: 'ismail' },
    emails: [ { value: 'ismailmammeripuse00@gmail.com', verified: true } ],
    photos: [
      {
        value: 'https://lh3.googleusercontent.com/a/ACg8ocJYvLb8f22dkwNU2IHjNrs0Wm4uW-U_MEXyoY3xOQbQNiu2IQ=s96-c'
      }
    ],
    provider: 'google',
    _raw: '{\n' +
      '  "sub": "111505623946860825036",\n' +
      '  "name": "ismail mammeri",\n' +
      '  "given_name": "ismail",\n' +
      '  "family_name": "mammeri",\n' +
      '  "picture": "https://lh3.googleusercontent.com/a/ACg8ocJYvLb8f22dkwNU2IHjNrs0Wm4uW-U_MEXyoY3xOQbQNiu2IQ\\u003ds96-c",\n' +
      '  "email": "ismailmammeripuse00@gmail.com",\n' +
      '  "email_verified": true\n' +
      '}',
    _json: {
      sub: '111505623946860825036',
      name: 'ismail mammeri',
      given_name: 'ismail',
      family_name: 'mammeri',
      picture: 'https://lh3.googleusercontent.com/a/ACg8ocJYvLb8f22dkwNU2IHjNrs0Wm4uW-U_MEXyoY3xOQbQNiu2IQ=s96-c',
      email: 'ismailmammeripuse00@gmail.com',
      email_verified: true
    }
  }
  ggggggg {
    res: <ref *1> ServerResponse {
      _events: [Object: null prototype] { finish: [Function: bound resOnFinish] },
      _eventsCount: 1,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: true,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: false,
      _closed: false,
      socket: Socket {
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _closeAfterHandlingError: false,
        _events: [Object],
        _readableState: [ReadableState],
        _writableState: [WritableState],
        allowHalfOpen: true,
        _maxListeners: undefined,
        _eventsCount: 8,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Server],
        _server: [Server],
        parser: [HTTPParser],
        on: [Function: socketListenerWrap],
        addListener: [Function: socketListenerWrap],
        prependListener: [Function: socketListenerWrap],
        setEncoding: [Function: socketSetEncoding],
        _paused: false,
        _httpMessage: [Circular *1],
        [Symbol(async_id_symbol)]: 20,
        [Symbol(kHandle)]: [TCP],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(shapeMode)]: true,
        [Symbol(kCapture)]: false,
        [Symbol(kSetNoDelay)]: true,
        [Symbol(kSetKeepAlive)]: false,
        [Symbol(kSetKeepAliveInitialDelay)]: 0,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
      },
      _header: null,
      _keepAliveTimeout: 5000,
      _onPendingData: [Function: bound updateOutgoingData],
      req: IncomingMessage {
        _events: [Object],
        _readableState: [ReadableState],
        _maxListeners: undefined,
        socket: [Socket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        rawHeaders: [Array],
        rawTrailers: [],
        joinDuplicateHeaders: null,
        aborted: false,
        upgrade: false,
        url: '/auth/google/callback?code=4%2F0ASVgi3IZq9M3xvHLl2tRy-O1VfHNGB-ZXOG2Lro-ritOl7hms-3IpEWigdsqmAYDJTWcFw&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=2&prompt=none',        
        method: 'GET',
        statusCode: null,
        statusMessage: null,
        client: [Socket],
        _consuming: false,
        _dumped: false,
        next: [Function: next],
        baseUrl: '',
        originalUrl: '/auth/google/callback?code=4%2F0ASVgi3IZq9M3xvHLl2tRy-O1VfHNGB-ZXOG2Lro-ritOl7hms-3IpEWigdsqmAYDJTWcFw&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=2&prompt=none',      _parsedUrl: [Url],
        params: {},
        query: [Object],
        res: [Circular *1],
        body: {},
        secret: undefined,
        cookies: [Object],
        signedCookies: [Object: null prototype] {},
        route: [Route],
        logIn: [Function (anonymous)],
        login: [Function (anonymous)],
        logOut: [Function (anonymous)],
        logout: [Function (anonymous)],
        isAuthenticated: [Function (anonymous)],
        isUnauthenticated: [Function (anonymous)],
        _sessionManager: [SessionManager],
        user: [Object],
        authInfo: {},
        [Symbol(shapeMode)]: true,
        [Symbol(kCapture)]: false,
        [Symbol(kHeaders)]: [Object],
        [Symbol(kHeadersCount)]: 38,
        [Symbol(kTrailers)]: null,
        [Symbol(kTrailersCount)]: 0
      },
      _sent100: false,
      _expect_continue: false,
      _maxRequestsPerSocket: 0,
      locals: [Object: null prototype] {},
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype] {
        'x-powered-by': [Array],
        'access-control-allow-origin': [Array],
        vary: [Array],
        'access-control-allow-credentials': [Array],
        'set-cookie': [Array]
      },
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    }
  }